import dynamic from 'next/dynamic';
import Head from 'next/head';
import Image from 'next/image';

import styles from '../styles/Home.module.css';

// use dynamic import component to avoid Hydration Mismatch
const Button = dynamic(() => import('../components/Button'), { ssr: false });

export default function Home() {
	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>
			<div className="dark:bg-black h-screen flex justify-center items-center">
				<Button />
			</div>
		</>
	);
}
